name: Update README

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          cd yujianke100
          echo '---' >> README.md
          echo 'permalink: /' >> README.md
          echo 'title: ""' >> README.md
          echo 'excerpt: ""' >> README.md
          echo 'author_profile: true' >> README.md
          echo 'redirect_from:' >> README.md
          echo '  - /about/' >> README.md
          echo '  - /about.html' >> README.md
          echo '---' >> README.md

      - name: Rename and move file
        run: |
          mv yujianke100/README.md yujianke100/about.md
          mv yujianke100/about.md yujianke100/yujianke100.github.io/_pages/
